### ISSUE TITLE
No `retain` for `Array` and `Table`/`TableLike`

### ISSUE THREAD

**Issue by jonhoo** [toml-rs/toml#311]
It's currently pretty painful to remove items matching a given condition from an array or table with `toml_edit` due to the lack of a `retain`-like method. You need one "pass" to gather the indices, and clone them if removing from a table, and then a second pass to remove each one, one by one. This is both unergonomic and inefficient. It'd be great to have `Array::retain` and `TableLike::retain` to make this kind of "match removal" easier!

**Comment by epage** [comment]
Agreed though right now I won't be able to get to this as I'm focused on prep work for cargo-add going into cargo.  Contributions would be welcome!

**Comment by marcospb19** [comment]
Love you both so I did #575.

`retain` should already be available to `Array` because it's a type alias to `Vec` :) .

**Comment by marcospb19** [comment]
Unlinking #575 to this issue because I did it for the wrong crate :laughing:, I might try again for the right one :sweat_smile: .

**Comment by marcospb19** [comment]
@epage you can close this.

I now realize that "Solves" [isn't a recognized keyword in GitHub](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) for linking PRs to issues.
