### ISSUE TITLE
Iterating over table gives different values then the `to_string()` method.

### ISSUE THREAD

**Issue by TimonPost** [toml-rs/toml#325]
I sort the keys of a table. When I sort them with `sort_values_by` and call `to_string()` they are not sorted. However, if I iterate over them they do seem sorted as I expect them to be. 

**iterating:**
This iterates the table printing the keys.
0: lib
1: bins
2: example

**to_string:**
This prints the entire table.
```
[lib]
a="b"
[example]
a="b"
[bins]
a="b"
```

For some reason, the to_string method doesn't seem to be affected by my sort operations.

**Comment by TimonPost** [comment]
This example reproduces it:
```rust
fn main() {
    let before = "[2]\n[1]\n[3]";
    let after = "[1]\n[2]\n[3]";

    let mut toml_document = before.parse::<toml_edit::Document>().unwrap();

    toml_document.sort_values_by(|k1, v1, k2, v2| {
        let a = k1.get().parse::<u8>().unwrap();
        let b = k2.get().parse::<u8>().unwrap();

        a.cmp(&b)
    });

    println!("to_string():");
    println!("{}", toml_document.to_string());

    println!("iterating:");
    toml_document.iter().enumerate().for_each(|(i, (k, v))| {
        println!("{}: {}", i, k);
    });

    assert_eq!(toml_document.to_string(), after);
}
```

**Comment by TimonPost** [comment]
Ah okay, thanks so the rust in-memory key-values dont map 1-1 to their toml key-value counterparts. Hence if I sort in memory they will not directly be sorted in the toml-variant. 

I will try doing as you suggested, sorting it in two phases and then updating it.

**Comment by TimonPost** [comment]
Assuming the document contains only tables, and with some dirty unwraps, this solves the issue. First storing all positions, then sorting, then mapping the new sorted elements to the positions their current index had before. 

```rust
   let mut toml_document = before.parse::<toml_edit::Document>().unwrap();

    let mut positions = Vec::new();

    toml_document.iter().for_each(|(k, t)| {
        positions.push(t.as_table().unwrap().position().unwrap());
    });

    toml_document.sort_values_by(|k1, _, k2, _| {
        let a = k1.get().parse::<u8>().unwrap();
        let b = k2.get().parse::<u8>().unwrap();

        a.cmp(&b)
    });

    toml_document
        .iter_mut()
        .enumerate()
        .for_each(|(i, (_, v))| {
            v.as_table_mut()
                .as_mut()
                .unwrap()
                .set_position(positions[i]);
        });
```

**Comment by epage** [comment]
Note that that does't handle recursive tables, like sorting the following
```
[workspace]

[workspace.package]

[workspace.dependencies]

[package]

[package.metadata]
```
