### ISSUE TITLE
Consider renaming the repo and adding a README at the root

### ISSUE THREAD

**Issue by ordian** [toml-rs/toml#341]
Could be renamed to toml or maybe you have better suggestions?

**Comment by epage** [comment]
> Could be renamed to toml or maybe you have better suggestions?

I think that makes sense.

Something I've been considering is if we should rename
- `toml` to `serde_toml`
- `toml_edit` to `toml`

If we had started from scratch, I feel like this is what we would have done **but** this would be very disruptive.

> adding a README at the root 

Any thoughts on what we should put in it besides an index of what crates are contained?

**Comment by samuelcolvin** [comment]
Readme would be very useful explaining the purpose of the difference crates.

For example from https://github.com/toml-rs/toml-rs/pull/464#issuecomment-1256393616 is toml-rs no longer maintained?

Should I switch [rtoml](https://github.com/samuelcolvin/rtoml) to use this library?

Frankly I'm a bit confused about that's going on.

With import repos like this, a README is a most.

**Comment by epage** [comment]
We now have a README that at least links to the contained crates with a brief description.  If you have feedback on what more is needed, I'd appreciate it.

Hopefully the repo name helps to clarify confusion over pushing people to `toml_edit` which is not the intent.  Should have done the rename before pointing people here.

The overall plan is move `toml` to be on top of `toml_edit`, see https://github.com/toml-rs/toml/issues/340

**Comment by samuelcolvin** [comment]
How does `toml_edit`s performance compare to `toml-rs`?

**Comment by epage** [comment]
Moved that conversation to #340 as I expect others will have a similar question.

**Comment by epage** [comment]
At this point, we've done the rename and have at least an index for a README
