### ISSUE TITLE
parse::<Document>() fails on a .toml file that uses format key.more_key = value

### ISSUE THREAD

**Issue by steviez** [toml-rs/toml#351]
Hello, first off, thank you for maintaining this crate!

I'm working on a project that recently upgraded to Rust 1.64, and we're looking to utilize the new feature that allows you to inherit keys for package(s) from a workspace Cargo.toml file. Just incase, some more reading [here](https://doc.rust-lang.org/cargo/reference/workspaces.html#the-package-table).

Upon updating my project to use this feature, a CI step that runs `cargo-sort` started failing with the following:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: TomlError { message: "TOML parse error at line 5, column 8\n  \|\n5 \| version.workspace = true\n  \|        ^\nUnexpected `.`\nExpected `=`\n" }', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/cargo-sort-1.0.7/src/sort.rs:113:46
--
  | stack backtrace:
  | 0: rust_begin_unwind
  | at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:584:5
  | 1: core::panicking::panic_fmt
  | at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:142:14
  | 2: core::result::unwrap_failed
  | at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/result.rs:1814:5
  | 3: cargo_sort::sort::sort_toml
  | 4: cargo_sort::_main
  | 5: cargo_sort::main
```
The unmangled line below is what choked it up, and the error message indicates that it doesn't like the dot.
```
version.workspace = true
```
I took a quick glance at the code, and it would seem that the `TomlParser` whose implementation starts below isn't equipped to handle kv pairs of this format.
https://github.com/toml-rs/toml/blob/5f43de763a5c93e4ace367428f7d84703308a4e9/crates/toml_edit/src/parser/document.rs#L80

**Comment by epage** [comment]
Could you give  more detailed reproduction steps?  We have test cases just like this and I just added this one in locally and was not able to reproduce it.

**Comment by steviez** [comment]
Ahh, I didn't do my diligence yesterday. I was also unable to recreate the issue with a minor test:
```rust
    #[test]
    fn test_document_parse() {
        let toml_string = String::from("[package]
                                        name = \"some_package\"
                                        version.workspace = true");
        let doc = &toml_string.parse::<Document>().expect("toml should parse");
    }
```
Upon closer inspection, I now see that `cargo-sort` is not using this `toml_edit` here
https://github.com/DevinR528/cargo-sort/blob/e6a795bc6b2c0958f9ef52af4863bbd7cc17238f/src/main.rs#L13
but rather, all of the source was pulled into `cargo-sort` repo at one point:
https://github.com/DevinR528/cargo-sort/tree/main/src/toml_edit

Apologies for the wild goose chase
