### ISSUE TITLE
I don't seem to have found any words about workspace

### ISSUE THREAD

**Issue by tu6ge** [toml-rs/toml#375]
This is about workspace [docs](https://doc.rust-lang.org/cargo/reference/workspaces.html#the-workspacepackage-table), 

My project has two crates, and I need `workspace` keyword unify version info, so, when I write toml file as this:

```
[package]
name = "bar"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
```

I try run [`changlog`](https://crates.io/crates/changelog) command failed, I checked their source code. They used this project to parse the toml file. but I dont found method of decode this syntax.

**Comment by epage** [comment]
This repo is for the [toml file format](https://toml.io/en/).  What you are asking about is the [cargo](https://github.com/rust-lang/cargo) schema and semantics though that isn't quite relevant here.

`changelog` is using [serde](serde.rs/) to define their understanding of the `Cargo.toml` schema.  It would be a feature request against `changelog` to add support for workspace inheritance.  Ideally they would switch to [cargo_metadata](https://crates.io/crates/cargo_metadata) for parsing which would give them all of the latest cargo features.

I will note that `changelog` also hasn't been touched in 2.5 years.

As this is a bug against `changelog` and not `toml`, I'm closing this out.
