### ISSUE TITLE
What changed in crate toml 0.5.9 to 0.5.10?

### ISSUE THREAD

**Issue by oxarbitrage** [toml-rs/toml#394]
Hi there, thank you for your work. We use the toml crate as a dependency in our project and i am having a hard time figuring out what changed from version 0.5.9 to 0.5.10, as the 0.5.9 is not a github branch.

In our case we use dependabot, for example https://github.com/ZcashFoundation/zebra/pull/5864 is bumping toml and https://github.com/ZcashFoundation/zebra/pull/5863 is another crate. Notice the changelog and commits are present in the later crate bump. 

It will be great if it can be fixed, if not a list of commits of whats new will help.

Thanks!

**Comment by epage** [comment]
Sorry, somehow I missed this issue.

toml 0.5.x is being tracked in the `toml-v0.5` branch (dependabot's commit link points you to the branch).  The main change was to update crates.io to point to the new repo location.  See https://github.com/toml-rs/toml/commits/toml-v0.5/crates/toml.
