### ISSUE TITLE
More `Error(UnsupportedType)` Feedback

### ISSUE THREAD

**Issue by dan-fritchman** [toml-rs/toml#396]
Really helpful library, thanks so much for your work on it. 

This issue is borne of https://github.com/dan-fritchman/Layout21/issues/33, in which: 

* I have a big tree of `struct`s, with lots of fields, internal types, and external types along the way
* I pass the biggest top-most one to `toml::to_string()`
* What comes back is this:

```
failures:

---- tests::empty_lib_to_toml stdout ----
thread 'tests::empty_lib_to_toml' panicked at 'save failed: Error(UnsupportedType)', gds21/src/tests.rs:214:50
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Question: is there any good way to get more than `UnsupportedType` as feedback here?  
(Set a setting, submit a PR to improve the error message, whatever.) 

Thanks again!

**Comment by epage** [comment]
Yes, ideally we report more details to help people with this.  However, a lot of things will be changing with #340 which I'm actively working on so I'd like to hold off on other changes until then.

**Comment by dan-fritchman** [comment]
Ok, cool, understand.
