### ISSUE TITLE
Consider making `Date`, `Time` etc. `Copy`

### ISSUE THREAD

**Issue by ModProg** [toml-rs/toml#427]
E.g. `Date` is only 32 bits, so IMO it would make sense to implement copy on it.

**Comment by epage** [comment]
`toml_datetime` is copy: https://github.com/toml-rs/toml/blob/main/crates/toml_datetime/src/datetime.rs#L80

So when we release `toml` 0.6, it will be `Copy` there as well

**Comment by epage** [comment]
I'm going to close this as resolved by #345
