### ISSUE TITLE
An error occurred deserializing u64

### ISSUE THREAD

**Issue by LULU233333** [toml-rs/toml#438]
```
use serde::{Deserialize, Serialize};

#[derive(Debug, Deserialize, Serialize)]
struct U64Test {
    value: u64,
}

fn main() {
    let text = toml::to_string(&U64Test { value: u64::MAX }).unwrap();
    println!("{text}");
    let _: U64Test = toml::from_str(&text).unwrap();
}
```

cargo run:
value = 18446744073709551615

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { inner: ErrorInner { kind: NumberInvalid, line: Some(0), col: 8, at: Some(8), message: "", key: [] } }', src\main.rs:11:44

**Comment by epage** [comment]
#442 verified that `toml_edit` does not have this problem and #457 moved `toml` to use `toml_edit`.  I'm going to close this as fixed.
