### ISSUE TITLE
Incorrect parsing of sub-hour timezone offsets

### ISSUE THREAD

**Issue by jorisvr** [toml-rs/toml#496]
toml-rs parses the following TOML document incorrectly:
```
d = 1911-01-01T10:11:12-00:36
```
This can be seen for example by running the example program `toml2json` which outputs:
```json
{
  "d": "1911-01-01T10:11:12+00:36"
}
```

It looks like the current `toml_datetime::Offset` structure is not even capable of representing a sub-hour negative offset.

This issue applies to the recent commit cc869e9dd5d87a2c7bee3fabcc94cbbed7538086 on main.

I'm experimenting with a TOML fuzzer which revealed this issue. I guess most normal applications are not likely to hit this case, so I understand if this gets low priority. It still seems worthwhile to fix it though.

**Comment by epage** [comment]
Yes, we likely need to change `toml_datetime::Offset::Custom` into forward and backward variants.

**Comment by epage** [comment]
Looking at API options for this
- `time` makes  [all fields negative](https://docs.rs/time/latest/time/struct.UtcOffset.html#method.from_hms) but they are private and a [constructor adjusts signs as needed](https://docs.rs/time/latest/src/time/utc_offset.rs.html#93)
- `chrono` also keeps the fields private but instead exposes [east/west constructors for seconds though that too is signed](https://docs.rs/chrono/latest/chrono/offset/struct.FixedOffset.html)
- Python's `datetime` uses a [time delta](https://docs.python.org/3/library/datetime.html#datetime.timezone)
- Java's `java.time` has the fields private with [different constructors that for H, H+M, H+M+S, with signs having to match](https://docs.oracle.com/javase/8/docs/api/java/time/ZoneOffset.html#ofHours-int-) (an exception?)

Aside: interesting that all of these APIs support timezone offsets with seconds but TOML does not.

So various options
- Track individual fields vs track minutes or seconds
  - As seconds isn't supported by TOML, that would make conversion ... interesting
- Public fields or private with accessors
  - Public keeps the API simple
  - Private allows ensuring invariants
  - Rest of the API is piblic atm
  - See also #188
- Signed per field or east/west variants
  - Separate variants would mean either a separate custom offset type of easier reuse or people having to get the fields out manually between the two variants
  - If multiple signed fields, that makes things confusing when signs are mixed.  Having constructors with private fields would help
  - Personally, I've found signed values easier to reason about

So stepping through decisions
1. Be consistent with rest of API, making the fields public
2. Reduce invalid cases that we can't enforce, so either
  - Signed minutes
  - East/West variants on `Offset`
3. `chrono`  only supports seconds (signed, east/west) while `time` supports signed seconds and signed HMS
  - Signed is the lowest common denominator but not by much
  - For "minutes", both crates will need conversion to/from seconds which is trivial (`time` has a `whole_minutes` getter)
  - HMS to seconds is not much more than minutes to seconds
  - 👎  chrono's seconds to toml HMS is an annoying conversion

So I have a slight leaning towards `Offset::Custom { minutes: i16 }`
