### ISSUE TITLE
Migrating from toml_edit::easy (Inline tables)

### ISSUE THREAD

**Issue by iovis** [toml-rs/toml#497]
Hi! Rust newbie here.

I have a very dumb question regarding the migration from `toml_edit::easy` to `toml v0.6.0` (which I'm assuming is the intended route after reading [this post](https://epage.github.io/blog/2023/01/toml-vs-toml-edit/))

I was using `toml_edit::easy::to_string()` to save a HashMap back into a toml file and it was rendering the tables inline, like so:
```toml
k = { name = "aoc2022", path = "/Users/david/Sites/aoc2022" }
```
`toml_edit = { version = "0.15.0", features = ["easy"] }`
[Full code](https://github.com/iovis/muxi/blob/master/src/sessions.rs#L21-L28)

I upgraded to `toml = { version = "0.6.0", features = ["preserve_order"] }` and changed the code:
```rs
// from
let toml = toml_edit::easy::to_string(&sessions)?;
// to
let toml = toml::to_string(&sessions)?;
```
And now the tables are expanded:
```toml
[k]
name = "aoc2022"
path = "/Users/david/Sites/aoc2022"
```

I couldn't find anything regarding configurability of this, and `to_string_pretty()` seemed to have the same behavior for this case in particular. Is there a way I could control whether I want the table to be serialized inline?

**Comment by epage** [comment]
With toml_edit 0.15's `to_string`, we left everything as inline tables.  To give this a try, render a large `Cargo.toml` with it.

To better match `toml`'s existing behavior, we switched to opportunistically rendering standard tables which is what users would expect more than deeply nested inline tables.  There are opportunities to improve this with `to_string_pretty` where we mix the table types.

**Comment by iovis** [comment]
Ohhh, I see!

I doubled down on `toml_edit` based on your comment:
```
// toml_edit = { version = "0.18.1", features = ["serde"] }

toml::from_str -> toml_edit::de::from_str
toml_edit::easy::to_string -> toml_edit::ser::to_string
```
And it's serializing into inline tables again.

Thank you!
