### ISSUE TITLE
Parsing with comment fails

### ISSUE THREAD

**Issue by ZimboPro** [toml-rs/toml#516]
When trying to parse a value with a comment using toml_edit (The comment is so that a comment will be added to the TOML file when writing back to the file)
`let value= "[] # Some comment".parse::<toml_edit::Item>().unwrap()`;
The following error occurs 
`TomlError { message: "", original: Some("[] # You can find the supported categories here https://crates.io/category_slugs"), keys: [], span: Some(2..3) }`

It occurs when trying to parse other types of values as well such as:
`let value= "true # Some comment".parse::<toml_edit::Item>().unwrap()`;

I am not sure if there is a better way to add comments to the Document/Item.

**Comment by epage** [comment]
You have two choices of what to `parse`
- A TOML document, with key/values, tables, comments, etc.  Use `toml_edit::Document`
- A TOML value which does not support leading/trailing whitespace, trailing comments, etc.  Use `toml_edit::Item` or `toml_edit::Value`.

In your case, it looks like you are trying to parse a value with comments.  You could do `format!("item = {}", value).parse::<Document>()` and then validate that only `"item"` is within the document.

**Comment by ZimboPro** [comment]
I am using toml_edit in my cargo-plugin [cargo-prepublish](https://github.com/ZimboPro/cargo-prepublish) which updates Cargo.toml to prepare for publishing. I would like to essentially insert a key/value pair with a comment in certain scenarios that are based on rules. eg `categories = [] # You can the find the categories at https://crates.io/category_slugs ` to help new users to find documentation and/or links.

So if I understand you correctly, I would create a temp Document, parse the string with the comment and then clone the Item and insert it into my existing Document for Cargo.toml?

**Comment by epage** [comment]
Thanks for sharing your use case; it helps a lot to know how to help.

Yes, that would be parsed as a `Document`.  Alternatively, if these are hard coded strings, you can generate the data structure directly.

**Comment by ZimboPro** [comment]
Do you have an example for that? That sounds perfect for my use case

**Comment by epage** [comment]
You can dig through cargo-edit (e.g. [dependency.rs](https://github.com/killercup/cargo-edit/blob/master/src/dependency.rs)) to see how we use it there.

The comment would be `decor` on your `Value` that you then `insert` into the appropriate table in your document.

**Comment by ZimboPro** [comment]
@epage Thanks for the help., it worked. Just a recommendation, maybe add a error message for it the value contains a comment, as the original error was just an empty string as can be seen in the first post. Let me know if you want to keep this open or close it since my issue was resolved but it did show an issue with the error message

**Comment by epage** [comment]
I tend to prefer not to repurpose issues as that can easily cause them to live forever.  We do have related issues that cover this on the implementation side, even if not in the exact same TOML syntax error.
