### ISSUE TITLE
unsure on how to migrate toml 0.5 to newer versions

### ISSUE THREAD

**Issue by sagiegurari** [toml-rs/toml#517]
toml as now breaking changes which are causing a mess for me and the changelog isn't documenting it well enough (for me) to understand how to resolve easily.

you can see the error here:
https://github.com/sagiegurari/cargo-make/actions/runs/4120362342/jobs/7115013610

serde_ignored is complaining:
error[E0277]: the trait bound `&mut toml::Deserializer<'_>: types::_::_serde::Deserializer<'_>` is not satisfied

i'm not even sure what other issues i'll run into next and whats the motivation around the breaking changes but i'm hoping they are not major.

would love some help here.

**Comment by epage** [comment]
I've updated the changelog with the missing entries.  You need to use an owned `Deserializer` rather than a `&mut` one.

**Comment by sagiegurari** [comment]
@epage thanks a lot!
