### ISSUE TITLE
Declaration order

### ISSUE THREAD

**Issue by gus4rs** [toml-rs/toml#520]
When parsing a toml file, I cannot obtain values from a map in the order they are declared:

```rs
use serde::Deserialize;
use std::collections::BTreeMap;

#[allow(dead_code)]
#[derive(Deserialize, Debug, Clone)]
pub struct Cfg {
    pub(crate) id: f32,
    pub(crate) accounts: BTreeMap<String, Account>,
}

#[allow(dead_code)]
#[derive(Deserialize, Debug, Clone)]
pub struct Account {
    pub(crate) id: i32,
    pub(crate) name: String,
}

fn main() {
    let toml = r#"

id=5

[accounts.f]
id=123
name="3a22e"

[accounts.u]
id=789
name="qawe"

[accounts.c]
id=456
name="3css"

[accounts.k]
id=1021
name="cfrt"

"#;

    let cfg: Cfg = toml::from_str(&toml).unwrap();

    for (id, name) in cfg.accounts.iter() {
        println!("({}, {:?})", id, name);
    }
}

```

Output:

```
(c, Account { id: 456, name: "3css" })
(f, Account { id: 123, name: "3a22e" })
(k, Account { id: 1021, name: "cfrt" })
(u, Account { id: 789, name: "qawe" })
```

What should I do? The toml format is not set in stone, is there a structure that would give me the declaration order, and still mapped to a custom struct?

**Comment by epage** [comment]
The problem is you are using a `BTreeMap` which defines what order you see things.  If you used `indexmap::IndexMap`, then order should be preserved.

**Comment by gus4rs** [comment]
Is there any alternative that doesn't require a external crate? Would a ```Vec``` of tuples work to map a list of accounts?

**Comment by epage** [comment]
I'd have to dig into the serde code to verify **but** you already are getting the `indexmap` crate via `toml_edit` so directly depending on it shouldn't be too much worse.

**Comment by gus4rs** [comment]
Great, thanks, that will do it
