### ISSUE TITLE
Have warning about "duplicate package" to run cargo build or test

### ISSUE THREAD

**Issue by lymslive** [toml-rs/toml#530]
When I pull this repo, run "cargo test", a waring is printed like:

```
warning: skipping duplicate package `example` found at `/home/tanshuil/.cargo/git/checkouts/libfuzzer-sys-e07fde05820d7bc6/35ce7d7/example_arbitrary`
```
Does that means the dependencies of this `toml` crate have duplicate package?
Although this is not error, it is noise, is there any way to depress this warning to let us feel better?

**Comment by epage** [comment]
A workspace member in the repo pulls in a git dependency.  When a git dependency has a duplicate package name, cargo produces a warning.  If the dependency is not being used then its not a problem.  This can't be suppressed.  Maybe one day once https://github.com/rust-lang/rfcs/pull/3389 is approved and merged, cargo will add support for suppressing warnings.
