### ISSUE TITLE
Unable to load data from `config.toml`

### ISSUE THREAD

**Issue by 9to1url** [toml-rs/toml#531]
I have issue with to reading the toml file in current folder. 

Error msg:
Unable to load data from `config.toml`

Here is the details:
- the code working fine on some linux/mac but failed on Ubuntu 20.04
- the binary is uploaded and config.toml file in same running folder

What I did:
- make sure the file is readable 
- no matter sudo or not sudo since the reading config.toml is the first line so both failed

Please advise what cause this issue? thanks

**Comment by epage** [comment]
Unfortunately, there is not much I can do without a reproduction case, both the `config.toml` in question and the rust code to load it.

**Comment by 9to1url** [comment]
if I remove the file, the error msg changed to:
```
Could not read file `config.toml`
```

**Comment by epage** [comment]
The above code is swallowing the error, printing its own version.  Could you print out the actual error?

Also, I'd need to see the definition of `Data`  to reproduce this on my side

**Comment by 9to1url** [comment]
// Top level struct to hold the TOML data.
#[derive(Deserialize)]
pub struct Data {
    pub config: Config,
}

and followed this tutorial:
https://codingpackets.com/blog/rust-load-a-toml-file/

**Comment by 9to1url** [comment]
Sorry, you can close this now, I by accident copied the debug version not the release one.

Thanks for you help a lot :-)
