### ISSUE TITLE
Retrieve spans for all values when parsing with `Table::from_str`.

### ISSUE THREAD

**Issue by iago-lito** [toml-rs/toml#533]
I have no prior expectation regarding the content of my TOML file, but I'm still willing to screen it and analyse the various values within it.  
As a consequence, I am not using the following pattern to parse the file:
```rust
#[derive(Deserialize)]
struct MyType {
    // .. because I could not decide what to write here.
}

let my_value: MyType = toml::from_str(input)?;
```

Instead, all I need to do is to parse the file into a plain `toml::Table`, and then iterate over it. But then I cannot retrieve the spans for the parsed values:
```rust
// Parse my file, without prior expectation regarding the content.
let table = Table::from_str(input)?;
// The file is valid TOML format. Good. Now start the analysis.
for (id, value) in table {
    // The values spans seem lost here: how can I raise/log/display/record information
    // regarding the values I'm analysing then?
}
```

Is there another way to use `Table::from_str` so that the `value`s yielded still contain span information? Or is there anything like a `toml::SpannedTable`? Would it be something that `toml-rs` would be willing to feature?

**Comment by epage** [comment]
At the moment, there is not a `SpannedTable`.  I believe it would effectively require us to duplicate all of `Table` and all the related types which would be quite the under taking and I would prefer not to take that on.  If people have a proposal for how to do this in a way that doesn't bloat the API or make it harder to use, I would be open to exploring it.

A lot of `Table`s design though is either for
- Supporting a variety of use cases
- Reduced compatibility guarantees
- Performance

You could make your own `SpannedTable` that is specialized to your use case and it should be relatively trivial to write (e.g. relying on the deriving `Serialize` and `Deserialize`)

**Comment by epage** [comment]
Closing in favor of people doing this on their side or #571
