### ISSUE TITLE
Deserialisation of non-existent field into `Vec<_>` type fails instead of empty vector

### ISSUE THREAD

**Issue by ActuallyHappening** [toml-rs/toml#550]
Hey, I don't know if this is intended, but the following code fails to run:

```rs
#[derive(serde::Deserialize)]
struct Test {
    field: Vec<String>,
}
let _: Test = toml::from_str(r##""##).expect("that _.test == vec![]");
```

with this error:
```
thread 'main' panicked at 'that _.test == vec![]:
Error {
inner: Error { 
inner: TomlError {
message: "missing field `field`", // <-- yes, but empty vector?
original: Some(""),
keys: [],
span: Some(0..0) } } }'
```

## Expected behaviour
That the `Test` struct would be instantiated with an **empty vector**.
If this is intended behaviour, how do I handle this other than wrapping `field` in an `Option` type?

**Comment by ActuallyHappening** [comment]
I have just remembered `#[serde(default)]` would solve this problem, but still am interested if this is expected behaviour

**Comment by cathaysia** [comment]
any process about this?

**Comment by epage** [comment]
I'd recommend looking at issues like #586 to see how to do this. Basically, contrast the same behavior in both `serde_json` and `toml`.  If they diverge, then thats a bug on our part.

**Comment by cathaysia** [comment]
Sorry, I used json so much that I forgot that toml is also part of the serde ecosystem. Adding serde(default) can indeed solve this issue. so why don't close this issue?
