### ISSUE TITLE
Deserialize from `toml::Value`?

### ISSUE THREAD

**Issue by RaitoBezarius** [toml-rs/toml#551]
I have a `toml::Value` somewhere and I would like to deserialize it to a structure and use the underlying deserializer, it seems everything is tailored around strings which makes it very difficult (?) to achieve this usecase.

Am I missing something?

**Comment by epage** [comment]
`Value` implements [`Deserializer`](https://docs.rs/toml/latest/toml/enum.Value.html#impl-Deserializer%3C'de%3E-for-Value) and provides a convenience wrapper in the form of [`Value::try_into`](https://docs.rs/toml/latest/toml/enum.Value.html#method.try_into).

Is that what you were looking for?

**Comment by RaitoBezarius** [comment]
Correct! Thank you!
