### ISSUE TITLE
Default value for "invalid type" error

### ISSUE THREAD

**Issue by Godnoken** [toml-rs/toml#561]
Hi there,

First of all, thank you very much for this crate. It's been very useful to me.

I'm building an application that will have an ever-changing configuration file and I would like to avoid resetting user's entire configs back to default as much as possible.

Let's say I have this simple field;

`````
hotkey: "ShiftLeft"
`````

and I then decide that I want it to be a struct with more fields such as;

````
[hotkey]
key: "ShiftLeft"
code: 160
````

Which would leave me with the error "invalid type: string" when using ``toml::from_str``

I know that empty fields can be set to default with ``#[serde(default)]``, but is there a way to make it return the default value when getting an invalid type?
I noticed the entire error message is private, so going that route to fix it seems to be a dead end.

Sorry if this is a question to be asked in one of the serde crates.

Thank you!

**Comment by epage** [comment]
What you are looking for is a serde feature called [Untagged Enums](https://serde.rs/enum-representations.html#untagged) which will let you deserialize a field as either a String or a Struct.

You have likely been the user of this feature if you think to creating a dependency: `toml = "0.9"` vs `toml = { version = "0.9" }`

**Comment by Godnoken** [comment]
> What you are looking for is a serde feature called [Untagged Enums](https://serde.rs/enum-representations.html#untagged) which will let you deserialize a field as either a String or a Struct.
> 
> You have likely been the user of this feature if you think to creating a dependency: `toml = "0.9"` vs `toml = { version = "0.9" }`

It wasn't exactly what I was looking for, but close enough that I would have used it, however, I found a different solution.
Thank you for the quick response & the extra trivia 😄 

What I ended up going with was;

````
#[derive(Serialize, Deserialize)]
#[serde(default)]
struct Config {
  #[serde(deserialize_with = "ok_or_default")]
  hotkey: Hotkey
}

fn ok_or_default<'a, T, D>(deserializer: D) -> Result<T, D::Error>
where
    T: Deserialize<'a> + Default,
    D: Deserializer<'a>,
{
    let v: Value = Deserialize::deserialize(deserializer)?;
    Ok(T::deserialize(v).unwrap_or_default())
}
````

Thanks to [dtolnay](https://users.rust-lang.org/t/solved-serde-deserialization-on-error-use-default-values/6681).
