### ISSUE TITLE
`Item::get_mut` behaves differently than `Item::get` when key doesn't exist

### ISSUE THREAD

**Issue by akmin04** [toml-rs/toml#577]
When using `Item::get_mut()` with a key that doesn't exist, the method returns `Some(Item::None)` as opposed to `Item::get()` which returns `None`.

## Example

```rust
use toml_edit::Document;

fn main() {
    let toml = "
    [a]
    ";

    let mut doc = toml.parse::<Document>().unwrap();
    let item = doc.get_mut("a").unwrap();

    let sub_item = &item.get("b");
    println!("{:?}", sub_item);

    let sub_item_mut = &item.get_mut("b");
    println!("{:?}", sub_item_mut);
}
```

### Output:
```
None
Some(None)
```

Is this intentional behavior? The docs for `get_mut` says `Returns ``None`` if ... The given key does not exist in the map` but it's unclear if that means `Option::None` or `Some(Item::None)`.

**Comment by epage** [comment]
The same is true for indexing.

I've been a bit mixed on this behavior.  The advantage is it makes it easier for doing deeply nested insertions of data.
