### ISSUE TITLE
What is the conceptual difference between `Item` and `Value`

### ISSUE THREAD

**Issue by tdejager** [toml-rs/toml#584]
Hi!

Trying to grok this library and I have a difficult time trying to figure out what the conceptual difference is between `Item` and `Value`. At first I thought Item is only `top-level` parts of the toml file.

But after seeing that

```rust
let doc = Document::new();
let bar = doc["foo"]["bar"];
```

Also returns an Item, I dont expect this to be true. Anyone able to clarify the distinction?

**Comment by epage** [comment]
An `Item` is a superset of `Value` that also includes `Table` and `ArrayOfTables`

So from your example
```toml
[foo.bar]
```
- `foo` is an Item that is a Table that points to `bar which is an Item that is a Table

**Comment by epage** [comment]
Closing this as it seems to be explained.
