### ISSUE TITLE
Newtype as the key of a `HashMap`/`BTreeMap` is not supported

### ISSUE THREAD

**Issue by TonalidadeHidrica** [toml-rs/toml#586]
A newtype - a named single-tuple type - cannot be used as the key of a `HashMap` or a `BTreeMap`.

[playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=ecabf606f065a4c82d7c4de0cb1c720d)
```rust
use std::collections::HashMap;
use serde::Deserialize;

#[derive(PartialEq, Eq, Hash, Debug, Deserialize)]
struct NewType(String);

fn main() -> anyhow::Result<()> {
    let map = toml::from_str::<HashMap<NewType, u32>>(r#"
    x = 1
    y = 2
    "#)?;
    println!("{map:?}");
    Ok(())
}
```

```
Error: TOML parse error at line 2, column 5
  |
2 |     x = 1
  |     ^
invalid type: string "x", expected tuple struct NewType
```

This is contrary to `serde_json`.

[playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=7c51f0b4d7b60349402c1cbad6a44bf1)
```rust
use std::collections::HashMap;
use serde::Deserialize;

#[derive(PartialEq, Eq, Hash, Debug, Deserialize)]
struct NewType(String);

fn main() -> anyhow::Result<()> {
    let map = serde_json::from_str::<HashMap<NewType, u32>>(r#"
    {"x": 1, "y": 2}
    "#)?;
    println!("{map:?}");
    Ok(())
}
```

```
{NewType("x"): 1, NewType("y"): 2}
```

I ran into this issue in my project, and I think that this should definitely be supported.

**Comment by m4tx** [comment]
Ran into the same issue today.

**Comment by m4tx** [comment]
Actually - this might be somewhat expected, as `NewType` does not seem to support deserialization from `&str` by default.

The solution is to modify the newtype so that it behaves just like the underlying type:
```rs
#[derive(PartialEq, Eq, Hash, Debug, Deserialize)]
#[serde(transparent)]
struct NewType(String);
```

With the addition of `#[serde(transparent)]`, the code posted in the issue seems to be working just fine.
