### ISSUE TITLE
Support serializing into inline tables

### ISSUE THREAD

**Issue by vlad-ivanov-name** [toml-rs/toml#592]
This issue is reopened from https://github.com/toml-rs/toml-rs/issues/265 as it's still relevant

Given the following set of structures:

```
#[derive(Serialize)]
struct Inner {
    value: i32,
}

#[derive(Serialize)]
struct Outer {
   value: Inner,
}

#[derive(Serialize)]
struct SomeDocument {
   value: HashMap<String, Outer>,
}
```

It would be good to have a way to serialize `Inner` values as inline tables. Currently, `to_string` will make everything inline, and `to_string_pretty` will make everything a full table. It would be good to control this per-field, perhaps with a custom field attribute like what serde does.

**Comment by epage** [comment]
serde does not provide a way for you to communicate intent.  That just leaves us coming up with some heuristic which I'd like to avoid.

However, you can instead serialize into a `toml_edit::Document` and the the `mod visit_mut` API to format it however you wish.  This is our generally recommended approach when people want custom formatting and so I'm planning to close this.  If you have a reason for us to re-open, let us know!
