### ISSUE TITLE
How to fix "expected a borrowed string" issue on custom deserializer when migrating from 0.5.x to 0.7.x?

### ISSUE THREAD

**Issue by davechallis** [toml-rs/toml#597]
I've recently tried upgrade from toml 0.5 to 0.7, and getting some errors when trying to use custom deserializers in serde that used to work with 0.5.x. I've read the changelog and can see some things related to that changed, but I couldn't figure out what was needed to fix it.

I've got a struct that can be deserialized from a bunch of different formats (including JSON and TOML). Here's a minimal example of the sort of thing that worked in 0.5, but gives me an error on 0.7:

[playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=2c7abf12208ea8d9b17b87556f868757)
```rust
use serde::{Deserialize, de::Deserializer};

#[derive(Deserialize)]
struct Config {
    #[allow(dead_code)]
    #[serde(deserialize_with = "deserialize_enabled_field")]
    enabled: bool,
}

fn deserialize_enabled_field<'de, D: Deserializer<'de>>(
    deserializer: D,
) -> Result<bool, D::Error> {
    let s: &str = Deserialize::deserialize(deserializer)?;
    Ok(match s {
        "yes" | "y" | "true" | "t" => true,
        _ => false
    })
}

fn main() {
    let json_data = r#" {"enabled": "true"} "#;
    let _: Config = serde_json::from_str(json_data).unwrap();
    
    let toml_data = r#" "enabled" = "true" "#;
    let _: Config = toml::from_str(toml_data).unwrap();
}
```

This gives the error:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { inner: Error { inner: TomlError { message: "invalid type: string \"true\", expected a borrowed string", original: Some(" \"enabled\" = \"true\" "), keys: ["enabled"], span: Some(13..19) } } }', src/main.rs:25:47
```

**Comment by epage** [comment]
You'll likely need to change
```rust
let s: &str = Deserialize::deserialize(deserializer)?;
```
to
```rust
let s: String = Deserialize::deserialize(deserializer)?;
```

**Comment by davechallis** [comment]
Thanks, I'll do some testing around that. In the real app the custom deserializer gets called millions of times (mostly from JSON), so I'll check if there's any performance impact from the switch.

**Comment by epage** [comment]
If so, you likely can improve the performance by using a custom deserialize visitor.
