### ISSUE TITLE
how to upgrade when using the tables_last feature

### ISSUE THREAD

**Issue by webern** [toml-rs/toml#613]
I have a package that is stuck on `0,5` because it is using `tables_last` https://github.com/bottlerocket-os/twoliter/blob/09734abc2f6f5d7d091fe0fc1b3307b8c96fc9cd/tools/testsys-config/src/lib.rs#L24

What is the upgrade path if we rely on this behavior?

Thank you for your help.

https://github.com/bottlerocket-os/twoliter/issues/51

**Comment by epage** [comment]
From the [0.7 changelog](https://github.com/toml-rs/toml/blob/main/crates/toml/CHANGELOG.md#breaking-change)

> Removed deprecated ser::tables_last as it isn't needed anymore

`tables_last` worked around a limitation in `toml` that no longer exists.

**Comment by webern** [comment]
Thank you. Closing.
