### ISSUE TITLE
The purpose of `serde_spanned`?

### ISSUE THREAD

**Issue by Kixunil** [toml-rs/toml#627]
Based on `serde_spanned` being a separate crate one would expect it's intended to be reused by other crates. However it's currently not possible without accessing hidden items. Is this planned? What is the purpose of the crate being separate?

**Comment by epage** [comment]
Yes, span tracking is independent of toml and there is the potential for it being shared, so I split it out.  If there is a crate looking to use it, and they have requests for what is needed, we can have issues open to work and resolve that.  As this isn't that, I'm closing this as the question is answered.  btw I would suggest a Discussion for something like this in the future.

**Comment by Kixunil** [comment]
Thanks for clarifying, I was in fact interested in using it in my crate [`rfc822-like`](https://docs.rs/rfc822-like/0.2.1/rfc822_like/index.html) but wasn't sure if that's something you intend to do.

I basically only need a stable way to emit `Spanned<T>` from my crate just like `toml` does. If you have a more specific question around that I can open an issue.

**Comment by epage** [comment]
> I basically only need a stable way to emit Spanned<T> from my crate just like toml does. If you have a more specific question around that I can open an issue.

Feel free to open an issue for what you need for using it in another serialization format.
