### ISSUE TITLE
Pre-commit is failing on spelling in one of toml-test's test fixtures

### ISSUE THREAD

**Issue by dtolnay** [toml-rs/toml#638]
I noticed this failure unrelated to my PR.

```console
 error: `Ue` should be `Use`, `Due`
  --> crates/toml_edit/tests/fixtures/invalid/bool/mixed-case-true.stderr:3:33
  |
3 | 1 | mixed-case-true         = trUe
  |                                 ^^
  |
```

I think this has been happening since https://github.com/toml-rs/toml/pull/630.

https://github.com/toml-rs/toml/actions/runs/6615797811/job/17968729592

**Comment by epage** [comment]
This was a bug in the pre-commit hook that was fixed in ed1fcb86e5b4649e1b75e00f3e4b29a018cc43a7
