### ISSUE TITLE
[BUG] - toml is not correctly using custom serialize impl 

### ISSUE THREAD

**Issue by oknozor** [toml-rs/toml#647]
Seems related to https://github.com/toml-rs/toml/issues/603, https://github.com/toml-rs/toml/issues/636

When serializing a struct containing `Option` with a custom serializer, we get an `UnsupportedType(None)` error. 
Note that this work as expected using toml < 0.5 and panic starting from 0.6. 

Here is a minimal reproducer: 
```rust
use std::fmt;
use std::fmt::Formatter;
use serde::{Serialize, Serializer};

struct Person {
    name: String,
    age: Option<u16>
}

impl Serialize for Person {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
        where
            S: Serializer,
    {
        serializer.serialize_str(&self.to_string())
    }
}

impl fmt::Display for Person {
    fn fmt(&self, f: &mut Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.name)
    }
}

fn main() {
    // Panics on toml = ^0.6
    // Works with toml = 0.5
    toml::to_string(&Person {
        name: "tom".to_string(),
        age: None,
    }).unwrap();
}
```

**Comment by epage** [comment]
This is serializing a string as a top-level TOML document which is invalid TOML syntax.  If you want to deserialize a TOML value, you can use `ValueSerailizer`.  As this is working as expected, I'm closing this,  If there is a reason for us to re-evaluate this, let us know!
