### ISSUE TITLE
(possible) bug between 0.5 and 0.8

### ISSUE THREAD

**Issue by yatesco** [toml-rs/toml#658]
Hi! I upgraded from 0.5 to the latest (0.8.8) and one of my tests failed (https://gist.github.com/rust-play/b702047bca3d2947c6d93120e96c1edb):

```rust
use serde::{Deserialize, Serialize};

#[derive(Debug, Serialize, Clone, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
pub enum Environment {
    Production,
    Development,
}

#[test]
fn environment_development() {
    let s = r#""development""#;
    let sut: Environment = toml::from_str(s).unwrap();
    assert_eq!(sut, Environment::Development);
}
```

I can't see *why* this test should now fail, so I'm wondering if this is a bug in the crate or my brain ;-).

Thanks for any help :-).

**Comment by Ltrlg** [comment]
This was an intentional breaking change in 0.6:

> - `from_str` now only parses toml documents, not values. See instead `de::ValueDeserializer`.

(from [changelog](https://github.com/toml-rs/toml/blob/main/crates/toml/CHANGELOG.md#060---2023-01-23))
