### ISSUE TITLE
Dependency on GLIBC introduced by toml::to_string function

### ISSUE THREAD

**Issue by Gunni** [toml-rs/toml#679]
Compiling a Rust program that uses the `toml` crate introduces a dependency on the system's GLIBC when using the toml::to_string function. This dependency causes compatibility issues when copying the binary to systems with different GLIBC versions.

Technical Details:
- Function with Dependency: toml_edit::encode::to_f64_repr
- Mangled Name: _ZN9toml_edit6encode11to_f64_repr17h38411fa9cfb09ff0E
- Source of Dependency: [toml_edit/src/encode.rs#L508](https://github.com/toml-rs/toml/blob/a20848d8a228605e2e4fa30b01c1a71d448de175/crates/toml_edit/src/encode.rs#L508)
- Symbol Causing Dependency: fmod

Minimal code to reproduce issue:
```rust
use serde::Serialize;

#[derive(Serialize)]
struct Foo<'a> {
    something: &'a str,
}

fn main() {
    let foo = Foo { something: "bar" };
    let _ = toml::to_string(&foo).unwrap();
}
```

```cargo.toml
[package]
name = "foo"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { "version" = "1.0", "features" = ["derive"] }
toml = "0.8"
```

Test dockerfile:
```dockerfile
FROM fedora:latest

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | bash -s -- -y
RUN dnf groupinstall -y "Development Tools"

RUN source "$HOME/.cargo/env" && \
	cargo init foo

WORKDIR /foo

COPY <<EOF /foo/src/main.rs
use serde::Serialize;

#[derive(Serialize)]
struct Foo<'a> {
    something: &'a str,
}

fn main() {
    let foo = Foo { something: "bar" };
    let _ = toml::to_string(&foo).unwrap();
}
EOF

COPY <<EOF /foo/Cargo.toml
[package]
name = "foo"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { "version" = "1.0", "features" = ["derive"] }
toml = "0.8"
EOF

RUN source "$HOME/.cargo/env" && \
	cargo build

RUN objdump -T target/debug/foo | grep GLIBC | sort -n \
	&& false # intentionally fail the build at this stage, remove to debug inside the container
```

Observe how the fmod line has the highest GLIBC version.

**Comment by epage** [comment]
We are using the standard library to convert a `f64` to a string. There are third party ways to do this (unsure if they use fmod) but aren't worth the dependency.

If you don't need `to_string`, you can disable it by disabling the associated feature.

I don't think there is anything more we can or should do for this, so I'm closing it. If there is a reason we should reconsider, let us know.

**Comment by busslina** [comment]
This workaround seems to work:

```bash
rustup target add aarch64-unknown-linux-musl
rustup component add rust-std-aarch64-unknown-linux-musl
```

```
[build]
target = "aarch64-unknown-linux-musl"

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-none-linux-gnu-gcc"

[target.aarch64-unknown-linux-musl]
linker = "aarch64-none-linux-gnu-gcc"
```
