### ISSUE TITLE
Deprecated field warning during deserialization

### ISSUE THREAD

**Issue by soywod** [toml-rs/toml#689]
Is there any way to generate a warning like the one produced by a `#[deprecated = "my warning"]` but at runtime, during deserialization of a TOML file content?

**Comment by epage** [comment]
There is not.  Your options are
- Deserialize into a generic form that supports the deprecated and undeprecated form, warn on one, and manually merge
  - I've done this at several points in `cargo-release`
- Deserialize normally but also parse to `toml::Value` and walk the structure, looking for specific patterns.

**Comment by epage** [comment]
To be clear. this isn't a `toml` limitation but a `serde` limitation.  For example, I'd love to have a way to have error recovery when deserializing but I don't think its possible.

**Comment by soywod** [comment]
> Deserialize normally but also parse to `toml::Value` and walk the
> structure, looking for specific patterns.

I will go for this option. Thank you for your reply!

**Comment by soywod** [comment]
I found an interesting third alternative that I would like to share here. I basically set up a custom deserializer that returns an error:

```rust
#[derive(Clone, Debug, Default, Eq, PartialEq, Serialize, Deserialize)]
pub struct A {
    #[serde(skip_serializing, deserialize_with = "my_deprecated_field")]
    pub b: Option<E>,
}

fn my_deprecated_field<'de, D: serde::Deserializer<'de>, T>(_: D) -> Result<T, D::Error> {
    Err(serde::de::Error::custom("deprecated field a.b, use c.d.e instead"))
}
```

```
Error: cannot parse config file at "[…]/config.sample.toml"

Caused by:
    TOML parse error at line 24, column 17
       |
    24 | a.b = "test"
       |                 ^^^^^^
    deprecated field a.b, use c.d.e instead
```
