### ISSUE TITLE
inclusion of another toml file and variable substitution

### ISSUE THREAD

**Issue by ssh352** [toml-rs/toml#692]
https://github.com/toml-lang/toml/issues/397 toml doesn't support inclusion of another toml file and variable substitution. Is anyone aware of any Rust crates preprocess toml files and support inclusion of another toml file and variable substitution? Thanks!

**Comment by epage** [comment]
Any pre-processing means you are no longer using TOML but something that evaluates to it. I the suggestion in the thread to design it into your schema is the way to go. Also may be worth considering if TOML is still the right choice.

**Comment by epage** [comment]
As this is unrelated to the development of the toml package, im going to go ahead and close.
