### ISSUE TITLE
How to serialize/deserialize while preserving formats with `toml_edit`?

### ISSUE THREAD

**Issue by yshui** [toml-rs/toml#733]
I tried wrapping all fields in `serde_spanned::Spanned`, but format is still not preserved. Do `toml_edit::{ser, de}` support preserving the format?

**Comment by epage** [comment]
`Spanned` is only if you want to track the locations.  There is no format preserving through serde.  This is not something that is even really feasible to do.  As such, I'm going to close this.  If there is a reason for us to keep this open, let us know!

**Comment by yshui** [comment]
@epage why do you think that is not feasible? I can come up with at least one way:

```rust
let doc = toml.parse::<DocumentMut>()?;
let value: T = from_document(&doc)?; // where T: Deserialize + Serialize
// modify value
to_document(&mut doc, value)?;
```

in `to_document`, if members of `value` serialize into existing values in the document, its formatting can be preserved.

**Comment by epage** [comment]
I took this issue to mean preserve through serde without sideband information. I feel side band information requires too many compromises. It at least should be proven out in viability and demand in a separate package before considering adopting it.
