### ISSUE TITLE
Bad span with untagged enum

### ISSUE THREAD

**Issue by nilehmann** [toml-rs/toml#748]
I'm getting the wrong spans with the following ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&code=use+toml%3B%0Ause+serde%3A%3ADeserialize%3B%0A%0A%23%5Bderive%28Deserialize%29%5D%0Astruct+S+%7B%0A++++key%3A+Vec%3CE%3E%2C%0A%7D%0A%0A%23%5Bderive%28Deserialize%29%5D%0A%23%5Bserde%28untagged%29%5D%0Aenum+E+%7B%0A++++A+%7B+a%3A+String+%7D%2C%0A++++B+%7B+b%3A+String+%7D%2C%0A%7D%0A%0Afn+main%28%29+%7B%0A++++let+s+%3D+r%23%22%0A%5B%5Bkey%5D%5D%0Aa+%3D+%22good%22%0A++++%0A%5B%5Bkey%5D%5D%0Ac+%3D+%22bad%22%0A%22%23%3B%0A++++if+let+Err%28err%29+%3D+toml%3A%3Afrom_str%3A%3A%3CS%3E%28s%29+%7B%0A++++++++println%21%28%22%7Berr%7D%22%29%0A++++%7D%0A%7D%0A))

```rust
use toml;
use serde::Deserialize;

#[derive(Deserialize)]
struct S {
    key: Vec<E>,
}

#[derive(Deserialize)]
#[serde(untagged)]
enum E {
    A { a: String },
    B { b: String },
}

fn main() {
    let s = r#"
[[key]]
a = "good"
    
[[key]]
c = "bad"
"#;
    if let Err(err) = toml::from_str::<S>(s) {
        println!("{err}")
    }
}

```

```
TOML parse error at line 2, column 1
  |
2 | [[key]]
  | ^^^^^^^
data did not match any variant of untagged enum E
```

I'd expect the error to be in line 5. I'm unsure if it's related to the untagged enum, but I've tried other variations without the untagged enum and it seems to work.

**Comment by epage** [comment]
This is an issue within `serde_derive`, see #535.  While the original post is focused on internally-tagged enums, it applies to that as well as untagged enums.  Closing in favor of that issue.  If there is a reason we should keep this open separately, let us know!
