### ISSUE TITLE
Table::try_into / Value::try_into not working

### ISSUE THREAD

**Issue by ItsSunnyMonster** [toml-rs/toml#749]
Whenever I try to use any of these functions, instead of the `try_into` provided by the types, the compiler thinks I am using the `try_into` function from `std::convert`. How can I get around this?

I am using Rust `1.79.0` and toml `0.8.14`.

**Comment by epage** [comment]
Can you provide a complete, minimal reproduction case with the compiler or runtime output that you don't expect, along with what you do expect?

**Comment by ItsSunnyMonster** [comment]
Here's the minimal reproduction case:

```rust
use toml::Table;
use serde::Deserialize;

fn main() {
}

#[derive(Deserialize)]
struct Deserialized {
    test: u32
}

// Dynamic type that needs a deserialize object
trait Dyn {
    type Deserialized: for<'de> Deserialize<'de>;
	
	// ...
}

// Type erased version which can be stored in a vector
trait TypeErasedDyn {
    fn deserialize(table: &Table);
	// ...
}

impl<T> TypeErasedDyn for T where T: Dyn {
	// Function to use the deserialize type
    fn deserialize(table: &Table) {
        let deserialized: T::Deserialized = table.try_into().unwrap();
    }
	// ...
}
```
Running `cargo build` gives
```
error[E0277]: the trait bound `<T as Dyn>::Deserialized: TryFrom<&toml::map::Map<std::string::String, Value>>` is not satisfied
  --> src/main.rs:22:51
   |
22 |         let deserialized: T::Deserialized = table.try_into().unwrap();
   |                                                   ^^^^^^^^ the trait `From<&toml::map::Map<std::string::String, Value>>` is not implemented for `<T as Dyn>::Deserialized`, which is required by `&toml::map::Map<std::string::String, Value>: TryInto<_>`
   |
   = note: required for `&toml::map::Map<std::string::String, Value>` to implement `Into<<T as Dyn>::Deserialized>`
   = note: required for `<T as Dyn>::Deserialized` to implement `TryFrom<&toml::map::Map<std::string::String, Value>>`
   = note: required for `&toml::map::Map<std::string::String, Value>` to implement `TryInto<<T as Dyn>::Deserialized>`
help: consider further restricting the associated type
   |
21 |     fn deserialize(table: &Table) where <T as Dyn>::Deserialized: From<&toml::map::Map<std::string::String, Value>> {
   |                                   +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

For more information about this error, try `rustc --explain E0277`.
error: could not compile `toml_repro` (bin "toml_repro") due to 1 previous error
```


The issue appears to be happening with dynamic types so this might not be an issue of the toml crate. Essentially what I have here is a trait that can hold any kind of type that can Deserialize into, and a type erased version of it which I can put in a collection like `Vec`.

It seems it has trouble detecting that the `T::Deserialized` type implements `Deserialize`.

**Comment by epage** [comment]
Could you provide a complete reproduction case that I can run locally, including a manifest?

**Comment by ItsSunnyMonster** [comment]
Sorry about the back and forth, here it is: [https://github.com/ItsSunnyMonster/toml_repro](https://github.com/ItsSunnyMonster/toml_repro)

**Comment by epage** [comment]
Thanks, that helped a lot!

The problem is that the signature id `Table::try_into(self: Table)` while you have a `&Table`.  To verify this, I made it `table.clone().try_into().unwrap()` and it compiled.

**Comment by ItsSunnyMonster** [comment]
Thank you so much! It works now. Sorry for wasting your time.
