### ISSUE TITLE
Implement `Serialize` and `Deserialize` for `Date` and `Time`

### ISSUE THREAD

**Issue by loqusion** [toml-rs/toml#763]
The [`v1.0.0` TOML spec][toml-spec] allows omission of the time or date portion of a [local date-time][toml-spec-local-date-time] to represent a [local date][toml-spec-local-date] or a [local time][toml-spec-local-time] respectively. However, there is currently no implementation for `Serialize` or `Deserialize` for [`Date`][toml-rs-date] or [`Time`][toml-rs-time] in the `toml` crate. While it is possible for consumers of `toml` to use [`Datetime`][toml-rs-datetime], it would be better to be able to use `Date`/`Time` directly to more clearly communicate intent, prevent mistakes in making runtime assertions, and avoid the need to manually unwrap the `date`/`time` `Option`s.

**NOTE:** I am not suggesting we interpret a local time as a duration as suggested in #696. [RFC 3339][rfc-3339-1] explicitly does not cover time intervals.

[rfc-3339-1]: https://datatracker.ietf.org/doc/html/rfc3339#section-1
[toml-spec]: https://toml.io/en/v1.0.0
[toml-spec-local-date]: https://toml.io/en/v1.0.0#local-date
[toml-spec-local-time]: https://toml.io/en/v1.0.0#local-time
[toml-spec-local-date-time]: https://toml.io/en/v1.0.0#local-date-time
[toml-rs-date]: https://docs.rs/toml/0.8.16/toml/value/struct.Date.html
[toml-rs-time]: https://docs.rs/toml/0.8.16/toml/value/struct.Time.html
[toml-rs-datetime]: https://docs.rs/toml/0.8.16/toml/value/struct.Datetime.html

**Comment by epage** [comment]
I am fine with someone implementing this.  I would expect the impl's to delegate to `Datetime` and then error if an unexpected field is set so we centralize all knowledge of the serde hacks we use to deserialize this time (and ensure full compatibility between them)
