### ISSUE TITLE
`SpannedVisitor` field order

### ISSUE THREAD

**Issue by shouya** [toml-rs/toml#789]
I'm attempting to implement span support for serde_yaml in a way compatible to serde_spanned. Specifically, I'd like to handle the magic struct in [`deserialize_struct`](https://github.com/shouya/serde-yaml-ng/blob/4162b22dac196f300982f93df3e29b829bde1aea/src/de.rs#L1713) from the [`DeserializerFromEvents`](https://github.com/shouya/serde-yaml-ng/blob/4162b22dac196f300982f93df3e29b829bde1aea/src/de.rs#L434) deserializer.

`DeserializerFromEvents` has a [`pos` ](https://github.com/shouya/serde-yaml-ng/blob/4162b22dac196f300982f93df3e29b829bde1aea/src/de.rs#L111) field that appear relevant, I'm trying detect the span based on this position cursor. However, due to the way `DeserializerFromEvents` works, it's impossible to extract `end` of the span the before parsing the value.

I thought about implementing [`SpannedDeserializer`](https://github.com/shouya/serde-yaml-ng/blob/4162b22dac196f300982f93df3e29b829bde1aea/src/de.rs#L1724C16-L1724C35) in a way that just wraps around `self: &mut DeserializerFromEvents<'de, 'document>`, so it can first spit out the starting `pos`, then the `value`, then the ending `pos`.

However, based on how [`SpannedVisitor`](https://github.com/toml-rs/toml/blob/091a0047931e997fe129f3c8fac2788af8091604/crates/serde_spanned/src/spanned.rs#L181) is implemented, it expect a strict order of keys to emit from my deserializer, which makes my plan unfeasible.

Based on my understanding of how serde_spanned works, making `SpannedVisitor` consume the keys in order of `start` > `value` > `end` (or `value`  > `start` > `end`) should make it flexible for use cases like mine. Or, for backward compatibility's sake, maybe it's better to allow `SpannedVisitor` consume the keys in arbitrary order. Or perhaps I'm doing it wrong and there is a better way to do it?

**Comment by epage** [comment]
When we controlled both sides, the order didn't matter and the current approach is much simpler to implement.

In making this easier for when its easier to generate the values in a specific order, I think its best to generalize it for maximum compatibility.

**Comment by epage** [comment]
btw would anything from #635 be useful?  It was blocked, pending feedback.

**Comment by shouya** [comment]
> would anything from https://github.com/toml-rs/toml/pull/635 be useful?

I don't think it's useful for my particular use case with a streaming parser where the span and value are not known upfront.
