### ISSUE TITLE
`de::Error` does not implement `source` method

### ISSUE THREAD

**Issue by dvzrv** [toml-rs/toml#800]
Hi! :wave: 

I'm using this crate in one of my projects [via confy](https://github.com/rust-cli/confy/blob/a7864eed4775f24fffc5dc58eb0aafd09f9f5f0b/src/lib.rs#L114) and really like its simplicity :ok_hand: 

Unfortunately I have been hit by a limitation. The `de::Error` type does not implement the `source` method, which prevents me from accessing its `inner`:

https://github.com/toml-rs/toml/blob/b05e8c489be8ebfc0acacc1ec3556d95cd8d2198/crates/toml/src/de.rs#L90

Is there a specific reason why this method is not implemented, or could this be changed? If so, I can provide a pull request if you want.

**Comment by epage** [comment]
Why do you need access to `inner`?

`source` serves as a way to provide the error that caused the current error.  UIs generally will print both error messages.  In our case, `de::Error` is a newtype and reporting it as the `source` would be both incorrect and cause it to be listed twice in some UIs

**Comment by dvzrv** [comment]
> Why do you need access to `inner`?
>
> `source` serves as a way to provide the error that caused the current error. UIs generally will print both error messages. In our case, `de::Error` is a newtype and reporting it as the `source` would be both incorrect and cause it to be listed twice in some UIs

I wanted to not print the outer Errors, but be able to print the specific TomlError.
Printing the chain was quite confusing in the use-case I had.

However, I think I bamboozled myself with a debug println (`println!("{:?}", error)`) into believing that I can't get to the message of the inner-most error (`toml::de::Error`, `toml_edit::de::Error` and finally `toml_edit::TomlError`).
Doing a `println!("{}", error)` on the `toml::de::Error` (wrapped by `ConfyError`) yields the desired behavior though, so I guess there is no need for any change after all.

Closing,  I guess implementations should rely on the fact that the `Display` implementation is delegated to the inner-most Error (in this case `toml_edit::TomlError`)?

**Comment by epage** [comment]
> I wanted to not print the outer Errors, but be able to print the specific TomlError.
> Printing the chain was quite confusing in the use-case I had.
>
> ...
>
> Closing, I guess implementations should rely on the fact that the Display implementation is delegated to the inner-most Error (in this case toml_edit::TomlError)?

So to verify, are you saying that everything is fine and this can be closed?

**Comment by wiktor-k** [comment]
>  In our case, de::Error is a newtype and reporting it as the source would be both incorrect and cause it to be listed twice in some UIs

Sorry to interrupt but I was looking at the PR. If the error is a new type shouldn't the source method invoke inner's source function? (To forward the call just like it does for Display's fmt).

**Comment by epage** [comment]
Technically, probably. However, the error we wrap doesn't implement that function, so it won't change anything.

**Comment by wiktor-k** [comment]
> Technically, probably. However, the error we wrap doesn't implement that function, so it won't change anything.

Yes, it won't change it now. But when the inner Error starts implementing `source` the developer would have to remember to also add it to the outer one.

(I don't have any issues with closing the ticket, this was just a remark). :wave:

**Comment by dvzrv** [comment]
> So to verify, are you saying that everything is fine and this can be closed?

I think this can be closed.

To my understanding the default print behavior for `ConfyError` is certainly out of scope for this issue tracker and relying on the `Display` impl of `toml::de::Error` (wrapped by `ConfyError`) seems to be what I am looking for!

Thanks again for the clarifications!
